### ISSUE TITLE
Broken link in help > "How it works"

### ISSUE THREAD

**Issue by egor83** [django-tenants/django-tenants#894]
`For more information please read the [setup](#setup) section.`

"Setup" link [in this section](https://github.com/django-tenants/django-tenants/blob/master/docs/index.rst#how-it-works) leads nowhere.

**Comment by tomturner** [comment]
Fixed — that section of `docs/index.rst` now ends with a working Sphinx cross-reference (``:doc:`use <use>```) instead of the dead `#setup` anchor. Thanks for reporting it.

**Comment by egor83** [comment]
Sorry to bother, but there's a couple of problems still:
1) when I read [the .rst file](https://github.com/django-tenants/django-tenants/blob/master/docs/index.rst#how-it-works) directly, the link looks weird:
<img width="631" height="50" alt="Image" src="https://github.com/user-attachments/assets/a25cbe2d-1d70-4ab1-9e7a-3a76b1a3374c" />

2) ...and if I click it, it just redirects me to the top of the same document, namely:
https://github.com/django-tenants/django-tenants/blob/master/docs/index.rst#id1
which is probably not the desired behaviour;
3) though [in the section on the homepage](https://github.com/django-tenants/django-tenants/tree/master#how-it-works), the link still reads "please read the [setup](https://django-tenants.readthedocs.org/en/latest/install.html) section", which might or might not be correct, I'm not sure what's the intended usage.

**Comment by tomturner** [comment]
Not a bother at all — you were right and I closed this too early. I checked `docs/index.rst`, saw a working `:doc:` reference, and didn't think to look at the README, which carries its own copy of the same paragraph with its own link. Reopened, and #1243 has a fix.

**On (3), the README:** that was a real bug. `.. _setup:` pointed at `install.html`, whose page is titled *Installation*, so the link text named a section that doesn't exist. It now reads `installation`_ and points to the same place, so text and destination agree. I've also moved the three `readthedocs.org` URLs to the canonical `readthedocs.io`.

I found one more while in there: `docs/index.rst` sent you to the **use** page, whereas the original broken `#setup` anchor and the README both meant installation. Both now point at installation.

**On (1) and (2) — the odd-looking link and the `#id1` redirect:** I can't fix those, and I'd rather say so than leave you expecting it. `:doc:` is a Sphinx role, and GitHub's `.rst` viewer doesn't implement Sphinx roles — it renders the role literally and invents an `#id1` anchor, which is exactly what you're seeing. Any Sphinx cross-reference in `docs/*.rst` will look wrong when browsed on GitHub; the rendered docs at https://django-tenants.readthedocs.io are the intended reading surface for that directory.

I did consider hard-coding the absolute readthedocs URL into `docs/index.rst` to make GitHub happy, but it would pin every reader to `/en/latest/` no matter which version they're on, and lose Sphinx's build-time link checking — a bad trade for the docs themselves.

What I have made sure of is that the **README** — the page GitHub renders as the project homepage, and where most people will hit that sentence — now has a plain absolute link that resolves properly.

Thanks for pushing back on this; it caught a genuine mistake on my part.

**Comment by egor83** [comment]
Okay, I see, and I agree with your reasoning. Leaving 1) and 2) be, I can confirm that 3) works as it should - README in project root now leads to where it says it leads, to "Installation" section.

And thanks a lot for this project! It was a great help for us :)
So you're welcome! Glad I could give back at least a little.

**Comment by tomturner** [comment]
Thanks for confirming — and for pushing back in the first place. You caught a close I'd made on a single `grep` of one file, which is exactly the kind of check that looks convincing and isn't. Glad the project's been useful.
